### ISSUE TITLE
move signature help container above current input line

### ISSUE THREAD

**Issue by appelgriebsch** [appelgriebsch/atom-ide-signature-help#1]

**Comment by laughedelic** [comment]
I'm not sure if it's related, but I have this artifact:

<img width="469" alt="Screenshot 2019-03-18 at 01 08 50" src="https://user-images.githubusercontent.com/766656/54500655-38f67300-491f-11e9-943f-046574e529a1.png">

Signature help is shown above the line and a symmetric empty box is shown below.

**Comment by laughedelic** [comment]
I tried removing the lines added in this commit and it did fix my issue: I see only one box with signature help below the line.
